version: '3.8'
services:
  pthm-clickhouse-flyway:
    image: 'clickhouse/clickhouse-server:${CHVER:-latest}'
    user: '101:101'
    container_name: pthm-clickhouse-flyway
    hostname: pthm-clickhouse-flyway
    volumes:
      - ./fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./fs/volumes/clickhouse/data:/var/lib/clickhouse
      - ./fs/volumes/clickhouse/logs:/var/log/clickhouse-server
      - ./fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ./fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
    ports:
      - '127.0.0.1:8125:8123'
      - '127.0.0.1:9004:9000'
    depends_on:
      - pthm-clickhouse-flyway-keeper
  pthm-clickhouse-flyway-keeper:
    image: 'clickhouse/clickhouse-keeper:${CHKVER:-latest-alpine}'
    user: '101:101'
    container_name: pthm-clickhouse-flyway-keeper
    hostname: pthm-clickhouse-flyway-keeper
    volumes:
      - ./fs/volumes/clickhouse-keeper/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
    ports:
      - '127.0.0.1:9185:9181'
#  db:
#    image: postgres:16.3-alpine3.20
#    container_name: PTHM-postgres
#    ports:
#      - "5435:5432"
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=pthm
#      - TZ=UTC
#      - PGTZ=UTC
#    volumes:
#      - ./data/postgres/:/var/lib/postgresql/data